package uk.l3si.eclipse.mcp.bpmn2.tools;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import uk.l3si.eclipse.mcp.bpmn2.Bpmn2Document;
import uk.l3si.eclipse.mcp.tools.Args;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class AddServiceTaskToolTest {

    private static final Gson GSON = new Gson();

    @TempDir
    Path tempDir;

    private AddServiceTaskTool tool;

    @BeforeEach
    void setUp() {
        tool = new AddServiceTaskTool();
    }

    private Path copyTestResource() throws Exception {
        Path target = tempDir.resolve("test-flow.bpmn2");
        try (InputStream in = getClass().getResourceAsStream("/test-flow.bpmn2")) {
            assertNotNull(in, "Test resource not found");
            Files.copy(in, target);
        }
        return target;
    }

    private JsonObject executeAndSerialize(JsonObject args) throws Exception {
        return GSON.toJsonTree(tool.execute(new Args(args), message -> {})).getAsJsonObject();
    }

    @Test
    void nameIsAddServiceTask() {
        assertEquals("bpmn2_service_task", tool.getName());
    }

    @Test
    void addServiceTask() throws Exception {
        Path file = copyTestResource();
        JsonObject args = new JsonObject();
        args.addProperty("file", file.toString());
        args.addProperty("name", "My Task");
        args.addProperty("taskName", "com.example.IService_doSomething");
        args.addProperty("displayName", "Do Something");
        args.addProperty("icon", "dynamo.gif");

        JsonObject result = executeAndSerialize(args);

        assertNotNull(result.get("id"));
        assertEquals("task", result.get("type").getAsString());
        assertEquals("My Task", result.get("name").getAsString());

        Bpmn2Document doc = Bpmn2Document.parse(file.toString());
        Element node = doc.findNodeById(result.get("id").getAsString());
        assertNotNull(node);
        assertEquals("task", node.getLocalName());
        assertEquals("My Task", node.getAttribute("name"));
        assertEquals("com.example.IService_doSomething",
                node.getAttributeNS(Bpmn2Document.NS_TNS, "taskName"));
        assertEquals("Do Something",
                node.getAttributeNS(Bpmn2Document.NS_TNS, "displayName"));
        assertEquals("dynamo.gif",
                node.getAttributeNS(Bpmn2Document.NS_TNS, "icon"));

        Element ioSpec = findChildElement(node, Bpmn2Document.NS_BPMN2, "ioSpecification");
        assertNotNull(ioSpec, "ioSpecification should exist");
        Element dataInput = findChildElement(ioSpec, Bpmn2Document.NS_BPMN2, "dataInput");
        assertNotNull(dataInput);
        assertEquals("ItemDefinition_1", dataInput.getAttribute("itemSubjectRef"));
    }

    @Test
    void autoGeneratedIdMatchesPattern() throws Exception {
        Path file = copyTestResource();
        JsonObject args = new JsonObject();
        args.addProperty("file", file.toString());
        args.addProperty("name", "Auto ID Task");
        args.addProperty("taskName", "com.example.IService_auto");

        JsonObject result = executeAndSerialize(args);

        String id = result.get("id").getAsString();
        assertTrue(id.matches("Task_\\d+"), "ID should match Task_N pattern, got: " + id);
    }

    @Test
    void customId() throws Exception {
        Path file = copyTestResource();
        JsonObject args = new JsonObject();
        args.addProperty("file", file.toString());
        args.addProperty("name", "Custom ID Task");
        args.addProperty("taskName", "com.example.IService_custom");
        args.addProperty("id", "MyTask");

        JsonObject result = executeAndSerialize(args);

        assertEquals("MyTask", result.get("id").getAsString());

        Bpmn2Document doc = Bpmn2Document.parse(file.toString());
        assertNotNull(doc.findNodeById("MyTask"));
    }

    @Test
    void duplicateIdThrowsError() throws Exception {
        Path file = copyTestResource();
        JsonObject args = new JsonObject();
        args.addProperty("file", file.toString());
        args.addProperty("name", "Duplicate");
        args.addProperty("taskName", "com.example.IService_dup");
        args.addProperty("id", "Task_1");

        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> tool.execute(new Args(args), message -> {}));
        assertTrue(ex.getMessage().contains("ID already taken"), ex.getMessage());
    }

    @Test
    void missingTaskNameThrowsError() throws Exception {
        Path file = copyTestResource();
        JsonObject args = new JsonObject();
        args.addProperty("file", file.toString());
        args.addProperty("name", "Missing TaskName");

        assertThrows(IllegalArgumentException.class,
                () -> tool.execute(new Args(args), message -> {}));
    }

    private static Element findChildElement(Element parent, String ns, String localName) {
        NodeList children = parent.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            if (children.item(i) instanceof Element el
                    && ns.equals(el.getNamespaceURI())
                    && localName.equals(el.getLocalName())) {
                return el;
            }
        }
        return null;
    }
}
